"""
Rocket League RPC CLI.
WARNING! This script is generated by Codex.
Only for development and debugging purposes, not intended for end-users.
"""

from __future__ import annotations

import argparse
import sys
import threading
import time

from backend.app_coordinator import AppCoordinator
from backend.config import config
from backend.constants import MAX_CONNECT_TRIES
from backend.logger import set_log_level, setup_logger

# ── ANSI colours (no external deps) ──────────────────────────────────────────

RESET = "\033[0m"
BOLD = "\033[1m"
DIM = "\033[2m"
GREEN = "\033[32m"
YELLOW = "\033[33m"
RED = "\033[31m"
CYAN = "\033[36m"
ORANGE = "\033[38;5;208m"


def _c(text: str, *codes: str) -> str:
    return "".join(codes) + text + RESET


# ── Status rendering ──────────────────────────────────────────────────────────


def _dot(connected: bool, pending: bool = False) -> str:
    if connected:
        return _c("●", GREEN)
    if pending:
        return _c("●", YELLOW)
    return _c("●", RED)


def _render_status(state: dict) -> str:
    discord = state.get("discord") or {}
    in_match = state.get("in_match", False)
    live = state.get("live_match_view") or {}

    tracker_on = state.get("connected") and state.get("listening")
    discord_on = discord.get("connected", False)
    requested = state.get("requested", False)

    tracker_label = (
        _c("Online", GREEN)
        if tracker_on
        else (_c("Connecting…", YELLOW) if requested else _c("Offline", RED))
    )
    discord_label = (
        _c("Online", GREEN)
        if discord_on
        else (
            _c("Reconnecting…", YELLOW)
            if discord.get("reconnecting")
            else _c("Offline", RED)
        )
    )

    lines = [
        "",
        f"  {_dot(bool(tracker_on), bool(requested))} Tracker  {tracker_label}    "
        f"{_dot(bool(discord_on), bool(discord.get('reconnecting')))} Discord  {discord_label}",
    ]

    if in_match and live:
        arena = live.get("arena") or "—"
        mode = live.get("mode") or "—"
        timer = live.get("time") or "—"
        status = live.get("status") or "—"
        t_score = live.get("team_score")
        o_score = live.get("opponent_score")
        score_txt = (
            f"{_c(str(t_score), ORANGE)}  —  {_c(str(o_score), CYAN)}"
            if t_score is not None and o_score is not None
            else "—"
        )

        lines += [
            "",
            f"  {_c('LIVE MATCH', BOLD)}",
            f"  {_c('Arena', DIM)}  {arena}   {_c('Mode', DIM)}  {mode}   "
            f"{_c('Timer', DIM)}  {timer}   {_c('Status', DIM)}  {status}",
            f"  {_c('Score', DIM)}  {score_txt}",
        ]
    else:
        lines.append(f"  {_c('No active match', DIM)}")

    lines.append("")
    return "\n".join(lines)


# ── Live loop ─────────────────────────────────────────────────────────────────


def _run_live(coordinator: AppCoordinator, stop: threading.Event) -> None:
    first = True
    prev_lines = 0

    while not stop.is_set():
        state = coordinator.get_live_state()
        output = _render_status(state)
        lines = output.count("\n") + 1

        if not first:
            # move cursor up to overwrite previous output
            sys.stdout.write(f"\033[{prev_lines}A\033[J")

        sys.stdout.write(output)
        sys.stdout.flush()
        prev_lines = lines
        first = False
        stop.wait(1.0)


# ── Preset subcommands ────────────────────────────────────────────────────────


def cmd_preset_list(coordinator: AppCoordinator) -> None:
    names = coordinator.list_presence_presets()
    if not names:
        print("No presets saved.")
        return
    for name in names:
        print(f"  • {name}")


def cmd_preset_load(coordinator: AppCoordinator, name: str) -> None:
    try:
        coordinator.load_presence_preset(name)
        print(_c(f"Preset '{name}' loaded.", GREEN))
    except ValueError as exc:
        print(_c(f"Error: {exc}", RED))


def cmd_preset_save(coordinator: AppCoordinator, name: str) -> None:
    try:
        coordinator.save_presence_preset(name)
        print(_c(f"Preset '{name}' saved.", GREEN))
    except ValueError as exc:
        print(_c(f"Error: {exc}", RED))


def cmd_preset_delete(coordinator: AppCoordinator, name: str) -> None:
    try:
        coordinator.delete_presence_preset(name)
        print(_c(f"Preset '{name}' deleted.", GREEN))
    except ValueError as exc:
        print(_c(f"Error: {exc}", RED))


# ── Entry point ───────────────────────────────────────────────────────────────


def build_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(
        prog="rl-rpc",
        description="Rocket League Discord Rich Presence — CLI",
    )
    p.add_argument("--no-tracker", action="store_true", help="Skip tracker connection")
    p.add_argument(
        "--no-discord", action="store_true", help="Skip Discord RPC connection"
    )
    p.add_argument("--quiet", action="store_true", help="No live status output")
    p.add_argument(
        "--log-level",
        default=None,
        metavar="LEVEL",
        help="Log level: DEBUG, INFO, WARNING (default: INFO)",
    )

    sub = p.add_subparsers(dest="command")

    preset = sub.add_parser("preset", help="Manage presence presets")
    preset_sub = preset.add_subparsers(dest="preset_cmd")
    preset_sub.add_parser("list", help="List saved presets")

    pl = preset_sub.add_parser("load", help="Load a preset")
    pl.add_argument("name")

    ps = preset_sub.add_parser("save", help="Save current config as preset")
    ps.add_argument("name")

    pd = preset_sub.add_parser("delete", help="Delete a preset")
    pd.add_argument("name")

    return p


def main() -> None:
    args = build_parser().parse_args()

    log_level = args.log_level or ("DEBUG" if config.development_mode else "INFO")
    setup_logger(log_file=config.log_path)
    set_log_level(log_level)

    coordinator = AppCoordinator()

    # ── Preset-only commands (no connection needed) ──
    if args.command == "preset":
        if args.preset_cmd == "list":
            cmd_preset_list(coordinator)
        elif args.preset_cmd == "load":
            cmd_preset_load(coordinator, args.name)
        elif args.preset_cmd == "save":
            cmd_preset_save(coordinator, args.name)
        elif args.preset_cmd == "delete":
            cmd_preset_delete(coordinator, args.name)
        else:
            print("Usage: cli.py preset {list|load|save|delete}")
        return

    # ── Live mode ────────────────────────────────────
    print(_c(f"\n  Rocket League RPC  v{config.app_version}", BOLD))
    print(_c("  Press Ctrl+C to stop\n", DIM))

    if not args.no_tracker:
        coordinator.connect_tracker()

    if not args.no_discord:
        threading.Thread(
            target=coordinator.connect_discord_rpc,
            kwargs={"max_tries": MAX_CONNECT_TRIES},
            daemon=True,
            name="discord-startup-connect",
        ).start()

    stop = threading.Event()

    if not args.quiet:
        live_thread = threading.Thread(
            target=_run_live, args=(coordinator, stop), daemon=True
        )
        live_thread.start()

    try:
        while not stop.is_set():
            time.sleep(0.1)
    except KeyboardInterrupt:
        stop.set()

    if not args.quiet:
        live_thread.join(timeout=1.0)

    print(_c("\n  Shutting down…", DIM))
    coordinator.shutdown()
    print(_c("  Done.\n", DIM))


if __name__ == "__main__":
    main()
